### ISSUE TITLE
Sir do anything not got any shiny Pokémon even after playing for three months

### ISSUE THREAD

**Issue by Falcon06YT** [poketwo/data#2]

**Comment by Falcon06YT** [comment]
Not got any shiny Pokémon even after playing 3 months

**Comment by NathNathNathNath** [comment]
How many pokemon are marked as "caught" when you use:
p!profile

**Comment by NathNathNathNath** [comment]
Mathematically, everyone *should* catch 1 shiny pokemon every 4096 pokemon catches.

Let's give an example:

Someone has caught 40,960 pokemon, but zero of them were shiny.

There's a 10% chance of that happening, which is a pretty low percentage, but not impossible. Nowhere near it in fact.

If this happened to someone, they have bad luck, nothing more.

I doubt this is actually a bug (its technically possible but like I said - I doubt it). I wish you better luck soon!

**Comment by cillosis** [comment]
**NOTE: I am horrible at math. Oliver is the math genius.**

Given 1/4096 odds means a **0.0244%** chance that the pokemon you catch will be shiny (i.e. success rate).

From what I can tell from a little research, you can get a rough guess on how many catches it might take by using one of the many statistical distribution models. My guess is this relies on a form of discrete probability distribution such as [geometric](https://www.statisticshowto.com/geometric-distribution/). With that distribution model, there are 3 main assumptions:

- There are two possible outcomes for each trial (success or failure). [i.e. its shiny or it is not shiny]
- The trials are independent. [i.e. each catch is not dependent on previous catches]
- The probability of success is the same for each trial. 

Ultimately my point is that even though there is a defined success rate, it is only a probability, not a guarantee. Theoretically, if incredibly unlucky, you could catch an infinite number of pokemon with 0 success. Or you could catch 10 pokemon and they are all shiny. Each catch is a separate probability trial and is not dependent upon previous catches or total catches (of course there is an exception when it comes to shiny hunt, which does things differently). Also you mentioned "after playing 3 months" -- you need to understand that this statistical model is not time dependent. In 3 months you could have only caught 1 pokemon or you could have caught many thousands. 

----

As an anecdote, when I first started playing, I caught two shinies on the first day within 200 catches. And, even more statistically improbable, they were from the same family (a Snivy and a Servine). Yet others have reached well over 10k catches without a single shiny. 

----

**Learn More:**
- https://math.stackexchange.com/questions/165993/average-number-of-times-it-takes-for-something-to-happen-given-a-chance
- https://opentextbc.ca/introbusinessstatopenstax/chapter/geometric-distribution/
- https://keisan.casio.com/exec/system/1180573193 (p = 0.0244 and x =number of catches without shiny)

**Comment by oliver-ni** [comment]
> Mathematically, everyone _should_ catch 1 shiny pokemon every 4096 pokemon catches.
> 
> Let's give an example:
> 
> Someone has caught 40,960 pokemon, but zero of them were shiny.
> 
> There's a 10% chance of that happening, which is a pretty low percentage, but not impossible. Nowhere near it in fact.
> 
> If this happened to someone, they have bad luck, nothing more.
> 
> I doubt this is actually a bug (its technically possible but like I said - I doubt it). I wish you better luck soon!
> 
> edit:
> I'm dumb so my math is probably wrong, but the point I'm making isn't lol

Yep, it's all luck—especially when you haven't caught many—however, larger numbers = conforms better to what you would expect.

In the special case of catching *all* or *no* shinies, it's really easy to calculate. If you've caught 40,960 pokémon, the chance of none of them being shiny is actually (4095/4096)^40960, or around 0.005%—not even anywhere close to 10%.

> From what I can tell from a little research, you can get a rough guess on how many catches it might take by using one of the many statistical distribution models. My guess is this relies on a form of discrete probability distribution such as [geometric](https://www.statisticshowto.com/geometric-distribution/). With that distribution model, there are 3 main assumptions:
> 
> * There are two possible outcomes for each trial (success or failure). [i.e. its shiny or it is not shiny]
> * The trials are independent. [i.e. each catch is not dependent on previous catches]
> * The probability of success is the same for each trial.

Yes! Actually, if you're calculating the probability for # shinies in a # catches, you would use the [binomial](https://en.wikipedia.org/wiki/Binomial_distribution) distribution. 

You can use the website [here](https://stattrek.com/online-calculator/binomial.aspx) and enter in `0.000244140625` (1/4096) for the probability _p_, the # pokémon for _n_, and the target # shinies for _x_.

You'll probably want to look at "Cumulative probability: P(X ≤ x)", which gives the probability (from 0 to 1) of catching _x_ shinies or fewer in _n_ catches.
