### ISSUE TITLE
Make nicknames alphanumerical only

### ISSUE THREAD

**Issue by NathNathNathNath** [poketwo/data#4]
Example of a pokemon I had traded to me:
![image](https://user-images.githubusercontent.com/39986236/103460090-74884a00-4d0b-11eb-9d04-261915396f7f.png)

The reason I think it would be a good idea is because it prevents nefarious links being added to nicknames.

Making them alphanumerical might also be a good preventative measure for potential database issues (I'm not a developer so my knowledge is limited, admittedly)

**Comment by kyle-he** [comment]
Pleas use https://github.com/oliver-ni/poketwo/issues instead.

**Comment by NathNathNathNath** [comment]
oops I thought I did! Thanks haha, will close this
